### ISSUE TITLE
使用反馈

### ISSUE THREAD

**Issue by littledavid-tech** [tencentyun/cosbrowser#1]
### 我的反馈
希望在以后的版本中能够添加多种文件的视图模式，目前的视图模式，如果文件名称太长了的话，文件名就会显示不全， 这有时候就会不太方便，如果说有列表视图的话就不回这样的问题了，期待下次更新。

**Comment by hbzhangwenjie** [comment]
安装后 ，打不来 ，双击 没反应

**Comment by carsonxu** [comment]
@hbzhangwenjie 系统信息截个图看看

**Comment by hbzhangwenjie** [comment]
![d](https://user-images.githubusercontent.com/13030314/46590745-4a259300-cae8-11e8-986b-8537216dc6b9.png)

**Comment by hbzhangwenjie** [comment]
![f](https://user-images.githubusercontent.com/13030314/46590849-3e869c00-cae9-11e8-9196-3ca7f594e806.png)

**Comment by carsonxu** [comment]
1.2.0 已支持列表布局，安装问题也再试试最新的 1.2.0 版本？
