### ISSUE TITLE
有没有Linux版本？

### ISSUE THREAD

**Issue by danielxu22** [tencentyun/cosbrowser#10]
有没有Linux版本？我用的是Ubuntu 16.04 64位，感谢！

**Comment by carsonxu** [comment]
暂时没有，我们后面会线支持 mac 版本，再看 ubuntu 版本兼容工作量。

**Comment by carsonxu** [comment]
https://github.com/tencentyun/cosbrowser/issues/45

**Comment by carsonxu** [comment]
linux 在 1.4.0 已支持
