### ISSUE TITLE
cosbrowser能否显示文件md5/文件大小(精确到字节)

### ISSUE THREAD

**Issue by renhaixyz** [tencentyun/cosbrowser#101]
如题，以往业务需要
迁移时这个没有，用起来很伤啊

**Comment by carsonxu** [comment]
可以在设置里“计算 meta-md5”，上传时会计算 md5 放在 x-cos-meta-md5 这个 Header 里。
上传后可以右键查看详情。有这个 md5 值。

**Comment by carsonxu** [comment]
已线下解决，另外COS 服务端增加了 crc 校验字段。暂时只对分片上传支持。后面会对简单上传也支持 crc 字段。
