### ISSUE TITLE
在任何界面误触到鼠标返回键会退回到登录界面

### ISSUE THREAD

**Issue by ixiumu** [tencentyun/cosbrowser#102]
再点击前进或者重新登录后回到了主界面...

**Comment by carsonxu** [comment]
没看明白什么意思，后面版本会加上前进后退按钮，是否解决？

**Comment by ixiumu** [comment]
加后退按钮的时候你就会发现了,我是带前进后退按钮的鼠标,在传输界面点返回 会直接返回到未登录状态
