### ISSUE TITLE
子用户只有一个桶内部分路径的权限，通过上方导航栏点击桶列表之后，失去访问原有路径的入口

### ISSUE THREAD

**Issue by helloxiaocui** [tencentyun/cosbrowser#103]
![image](https://user-images.githubusercontent.com/9263012/76318778-2d167480-6319-11ea-9961-2be4b04c1fe8.png)
点击后表现如下，无法返回原有访问内容，只能退出登录
![image](https://user-images.githubusercontent.com/9263012/76318823-3dc6ea80-6319-11ea-88ba-36ca6743cf09.png)

建议解决办法：
1. 客户端记录本地可访问路径的上级路径，误点到根目录后能逐级返回；
2. 提醒用户不要点击无法访问的上级路径，否则可能导致无法返回。

**Comment by carsonxu** [comment]
谢谢建议，这我们考虑加上优化。

**Comment by carsonxu** [comment]
v2.1.0 已支持路径前进后退
