### ISSUE TITLE
2.0之后的版本在复杂权限控制方面有很多退步，建议重新梳理

### ISSUE THREAD

**Issue by helloxiaocui** [tencentyun/cosbrowser#104]
换了新版后，发现权限管理方面很多功能还不如老版本，不能为了UI优化失去原有功能啊！建议产品经理好好梳理一下，补齐
1. 添加访问路径时，确定按钮经常不可用（事实上我就没见它可用过）
![image](https://user-images.githubusercontent.com/9263012/76486601-bda89e00-645a-11ea-89f3-cb119b7ad337.png)
2. 在登录页填的访问路径，没法记录在“存储桶列表”里，再加上上一个issue反馈的bug（误点击到上层目录无法返回），导致动不动就失去入口，只能重新退出登录；

事实上，我给一个子账号开了一个桶下两个目录的读写权限，在之前的版本，这两个路径是可以添加并访问的。现在这个版本，这个最简单的功能就成了奢望

**Comment by carsonxu** [comment]
这里是有 bug，判断 / 就不允许添加，我们尽快更新修复。
你可以先让子帐号登录控制台，添加访问路径，也能在cosbrowser生效。
一会先给你个临时版本。贴到这个 issue 里。

**Comment by carsonxu** [comment]
https://cos5.cloud.tencent.com/cosbrowser/cosbrowser-setup-beta.exe

**Comment by helloxiaocui** [comment]
多谢

**Comment by carsonxu** [comment]
2.0.2已修复“无法添加路径问题”
