### ISSUE TITLE
上传经常会卡住或者报一些未知错误

### ISSUE THREAD

**Issue by tommyfok** [tencentyun/cosbrowser#105]
![image](https://user-images.githubusercontent.com/3250229/76588385-d8921580-6521-11ea-9a27-b6c2c584a04b.png)

**Comment by carsonxu** [comment]
这个是 iOA 问题导致的，有时候某些请求卡住，等60秒超时才会继续，内部使用可以联系 carsonxu。

**Comment by tommyfok** [comment]
> 这个是 iOA 问题导致的，有时候某些请求卡住，等60秒超时才会继续，内部使用可以联系 carsonxu。

谢谢

**Comment by carsonxu** [comment]
这里确认下，是否有选择 “使用HTTPS” ？sns cos 需要选上。

**Comment by carsonxu** [comment]
确认了问题是没有使用 HTTPS 导致
