### ISSUE TITLE
feature 水印支持

### ISSUE THREAD

**Issue by simonisacoder** [tencentyun/cosbrowser#108]
能否支持上传时自动增加水印

**Comment by carsonxu** [comment]
上传不考虑支持，你可以下载的时候使用数据万象接口。
https://cloud.tencent.com/product/ci

**Comment by simonisacoder** [comment]
或者可以在存储桶配置，下载的时候，如果是图片类型，自动加水印，不必走万象接口，用途是希望博客图片被下载时，自动加水印

**Comment by carsonxu** [comment]
COS 下载链接本身就支持加水印的，你试试在 url 后面追加：
?imageMogr2/interlace/0|watermark/2/text/5rC05Y2w/font/bXN5aGJkLnR0Zg/fontsize/72/fill/IzAwMDAwMA/dissolve/30/gravity/southeast/dx/30/dy/30
