### ISSUE TITLE
同步本地文件夹的功能

### ISSUE THREAD

**Issue by Royce2019** [tencentyun/cosbrowser#111]
已经关闭了自定同步，然后手动点击开始同步
能不能把每次同步的文件列出来然后对每个文件进行手动确认
经常我文件夹加了一张图片进去，但是一点开始同步，同步日志里就冒出来好多条同步信息，根本不知道为什么就把那些没动过的文件又传了一次

**Comment by carsonxu** [comment]
这里其实没再次上传，只是做了 md5 对比，确认了一致。
后面优化下文字提示，对“上传成功”和“对比一致，不需要上传”两种情况区分对待。

**Comment by Royce2019** [comment]
好的谢谢

**Comment by Chandler-Lu** [comment]
> 这里其实没再次上传，只是做了 md5 对比，确认了一致。
> 后面优化下文字提示，对“上传成功”和“对比一致，不需要上传”两种情况区分对待。

您好，目前仅支持本地->云端同步，不知道有没有计划支持云端->本地的反向同步，或者直接支持双向同步呢？

**Comment by Royce2019** [comment]
同问，而且目前好像不支持下载整个储存桶

**Comment by Chandler-Lu** [comment]
> 同问，而且目前好像不支持下载整个储存桶

主要他们似乎放弃了对原生ftp的支持，不知道为啥。。如果支持一些通用协议比如webDAV或者ftp之类的，可能会更好

**Comment by Wonder233** [comment]
在 2.x.x 以后的版本中，下载整个存储桶的功能放在了文件列表右键菜单中。
<img width="150" alt="download" src="https://user-images.githubusercontent.com/8199240/79725653-21589d80-831c-11ea-86b8-a03afaddf2bd.png">
在根目录点击即可下载整个存储桶。
