### ISSUE TITLE
开始版本控制失败,如何解决?

### ISSUE THREAD

**Issue by wan9zh1hu1** [tencentyun/cosbrowser#112]
使用cosbrowser托管静态网站时,开启版本控制失败
cosbrowser版本 v2.0.3
macOS Catalina 10.15.4

**Comment by wan9zh1hu1** [comment]
提示信息为:版本控制设置失败[object Object]

**Comment by Wonder233** [comment]
同步页面开启版本控制失败的错误提示不正确，将在 2.1.0 版本修复。

这里先提供一个解决方案：打开存储桶详情编辑版本控制。

**Comment by wan9zh1hu1** [comment]
> 同步页面开启版本控制失败的错误提示不正确，将在2.1.0版本修复。
> 
> 这里先提供一个解决方案：打开存储桶详情编辑版本控制。
详情中显示:

地域	ap-shanghai
访问权限	私有读写 
版本控制	没权限获取

**Comment by Wonder233** [comment]
您应该是子账号没有访问和编辑存储桶版本控制的权限，可以联系主账号授予 getBucketVersioning 和 putBucketVersioning 的权限。

**Comment by Wonder233** [comment]
感谢您提出的问题，后续版本将会加入更丰富的权限提示信息。
