### ISSUE TITLE
支持生成自定义加速域名

### ISSUE THREAD

**Issue by Chandler-Lu** [tencentyun/cosbrowser#113]
对于公有桶，大部分情况下用户需要以自定义域名来进行访问，而不是默认域名。
目前网页版是可以生成自定义域名链接的，但是客户端暂时没看到这个功能，希望可以增加该功能，并允许用户开启在点击分享按钮时，默认复制自定义域名。
![Snipaste_2020-04-18_22-17-46](https://user-images.githubusercontent.com/18322610/79640150-91531080-81c2-11ea-9947-07510013d26c.png)
![Snipaste_2020-04-18_22-18-19](https://user-images.githubusercontent.com/18322610/79640153-944e0100-81c2-11ea-835e-06dfcb188dca.png)

**Comment by Wonder233** [comment]
您好，感谢您提出的建议。
该功能已在开发中，将在 2.1.0 版本发布。
