### ISSUE TITLE
显示问题

### ISSUE THREAD

**Issue by JalenChuh** [tencentyun/cosbrowser#115]
2.1.0版本

在窗口较小的情况储存桶中显示有问题

![image](https://user-images.githubusercontent.com/57910033/79999894-0ee28d80-84ef-11ea-8dec-37d4a66ea1cb.png)

**Comment by carsonxu** [comment]
什么系统？我这边拖到最小后，站考左侧存储桶列表都不会。

**Comment by Royce2019** [comment]
win10

**Comment by Royce2019** [comment]
展开列表才会

**Comment by Royce2019** [comment]
![Snipaste_04-22_23-23-48](https://user-images.githubusercontent.com/57910033/80001130-9aa8e980-84f0-11ea-91e2-5dac9d4e0e8b.png)

储存桶的名字还有一定几率显示成这样

**Comment by carsonxu** [comment]
好的，谢谢，我们再优化下。

**Comment by carsonxu** [comment]
再问一句，屏幕的分片率多大？

**Comment by Royce2019** [comment]
1920 x 1080

**Comment by Wonder233** [comment]
您好，2.1.1 版本已发出，窄屏显示已修复。

**Comment by Royce2019** [comment]
![image](https://user-images.githubusercontent.com/57910033/80181753-09dd2580-8638-11ea-964f-a30105dd3375.png)
![Snipaste_04-24_14-28-56](https://user-images.githubusercontent.com/57910033/80181770-0fd30680-8638-11ea-9dd2-99ab98cf0e66.png)
还有个问题，也是窗口缩小出现的
图1是出现问题的时候

**Comment by Wonder233** [comment]
请问是哪个版本？

**Comment by Royce003** [comment]
2.1.4
