### ISSUE TITLE
上传大量文件特别慢

### ISSUE THREAD

**Issue by BeatMicrosoft** [tencentyun/cosbrowser#117]
我设置了上传100个，特别慢。。。。上两个版本，还不是新UI界面的时候，特别快，我设置上传100，那速度嗖嗖的。。。。你们更新的什么垃圾玩意儿？你们测试过么？上传8000个文件？还特别容易卡，什么客户端？？？？win/mac都是如此，更新的真垃圾
能不能麻烦处理下。

**Comment by BeatMicrosoft** [comment]
或者你们能不能告诉我，怎么回滚老版本？

**Comment by carsonxu** [comment]
https://github.com/tencentyun/cosbrowser/blob/master/changelog.md
感谢反馈，我们尽快排查，历史版本 1.5.4 在这个链接下载。

**Comment by BeatMicrosoft** [comment]
> https://github.com/tencentyun/cosbrowser/blob/master/changelog.md
> 感谢反馈，我们尽快排查，历史版本 1.5.4 在这个链接下载。

非常感谢，使用老版本后，速度又嗖嗖的了。。 希望你们推出下一个版本一定要测试一下多文件上传

**Comment by cheneboy** [comment]
都2.2.2版本了，上传文件问题还没解决吗？昨晚11点上传9万个文件，本来今天可以测试，结果到第二点12点多依然卡在9999+!!现在我用了1.5.4版本上传非常快，上传问题搞这么久都没搞好，如果是我手下，我早就炒掉他了！

**Comment by carsonxu** [comment]
v2.5.0 已修复
