### ISSUE TITLE
请问怎么设置默认域名？

### ISSUE THREAD

**Issue by daqueque** [tencentyun/cosbrowser#119]
桶已经绑定了自己的域名dl.xxx.com

怎么实现在点击分享的按钮，复制的就是自己的域名

**Comment by Wonder233** [comment]
有两个入口：
1. 右键复制链接可进行选择。
![image](https://user-images.githubusercontent.com/8199240/81561097-39748780-93c5-11ea-882d-7e7ceeb96c6c.png)
2. 点击更多图标，点击分享
![image](https://user-images.githubusercontent.com/8199240/81561196-632dae80-93c5-11ea-9661-a7e283c6f9d2.png)
