### ISSUE TITLE
右侧弹层没法收起

### ISSUE THREAD

**Issue by rawbin-** [tencentyun/cosbrowser#120]
![image](https://user-images.githubusercontent.com/8169783/81719931-4a4df780-94b0-11ea-8d84-df4b0382053d.png)

**Comment by carsonxu** [comment]
感谢反馈，这个 popup 某些操作下，会出现这个问题。下个版本会改为 dialog。

**Comment by carsonxu** [comment]
v2.3.0 有优化，改为了弹窗
