### ISSUE TITLE
右键新建文件夹会闪退，经常出现

### ISSUE THREAD

**Issue by sinfere** [tencentyun/cosbrowser#121]

**Comment by BeatMicrosoft** [comment]
还有右键拷贝链接的时候，新建文件夹也容易闪退。

不是，腾讯是不管这个部门了么？做的个什么垃圾软件？多文件上传的问题解决了么？半年了！

**Comment by Wonder233** [comment]
可以告知一下操作系统及操作系统版本吗？

**Comment by sinfere** [comment]
> 可以告知一下操作系统及操作系统版本吗？

macOS 10.15

**Comment by Wonder233** [comment]
v2.4.0 版本已修复该问题。
