### ISSUE TITLE
是否能够支持同时打开多个客户端，分别登录不同的帐号？

### ISSUE THREAD

**Issue by evan-xia** [tencentyun/cosbrowser#122]
win10系统，最新版本（v 2.1.4），测试还不支持。

**Comment by carsonxu** [comment]
暂不支持，什么场景要打开多个？

**Comment by evan-xia** [comment]
比如我有多个cos帐号，如果只支持单个窗口，每次切换需要重新登录一遍，交互不友好。

**Comment by Wonder233** [comment]
当前最新版本 2.4.1 支持在已登录的情况下进行账号切换，是否能解决您的问题？
