### ISSUE TITLE
windows 桌面版勾选“计算并添加 x-cos-meta-md5 头部”时候没有这个 header

### ISSUE THREAD

**Issue by fyears** [tencentyun/cosbrowser#125]
版本：windows v2.2.2 （下载于 20200712）

复现：勾选“计算并添加 x-cos-meta-md5 头部”，上传文件。

期待：右键查看上传完毕的文件的“详情”能看到对应 header
实际：没有对应 header

**Comment by Wonder233** [comment]
你好，v2.4.0版本开始将下掉该功能。现在 COS 默认支持更高准确性的 crc64 校验。
