### ISSUE TITLE
大量队列上传时，客户端十分卡顿；扫描同步功能建议

### ISSUE THREAD

**Issue by awsyork** [tencentyun/cosbrowser#130]
win10，CPU资源占用60%以下，从数据盘（SSD）上传7000+文件，软件安装在系统盘（SSD），客户端**所有交互都十分卡顿**，反应很慢。

另：希望增加PC端指定目录**文件扫描与自动同步** 功能

**Comment by carsonxu** [comment]
卡顿问题 2.5.0 已优化。
支持文件同步的，在界面上右上角有按钮进入可以设置。
