### ISSUE TITLE
大批量上传文件的时候 会经常卡死，而且传不动

### ISSUE THREAD

**Issue by 815584445** [tencentyun/cosbrowser#132]
在windows server 2019系统 以及windows10 里面都有测试过
上传9万个图片文件 速度会很慢 然后会经常性卡死需要重启

**Comment by carsonxu** [comment]
感谢反馈，正在优化这个问题。
可以先用 coscmd 或 [v1.5.4](https://cos5.cloud.tencent.com/cosbrowser/cosbrowser-setup-1.5.4.exe)

**Comment by carsonxu** [comment]
v2.5.0 已优化上传性能。
