### ISSUE TITLE
不显示自定义CDN加速域名

### ISSUE THREAD

**Issue by mouse0232** [tencentyun/cosbrowser#133]
我在腾讯云后台显示有自定义cdn加速域名，但是在cosbrowser没有，并且提示默认加速域名关闭。我使用根帐号登录的。

**Comment by mouse0232** [comment]
说明cosbrowser版本是2.4.1

**Comment by Wonder233** [comment]
可以多提供一点信息吗？
麻烦提供一下控制台自定义 cdn 域名状态以及 cosbrowser 里自定义 cdn 域名状态的截图。

**Comment by mouse0232** [comment]
> 可以多提供一点信息吗？
> 麻烦提供一下控制台自定义 cdn 域名状态以及 cosbrowser 里自定义 cdn 域名状态的截图。

cosbrowser显示下图
![Image of Yaktocat](https://i.niupic.com/images/2020/11/03/8WN7.png)

腾讯云后台显示下图
![Image of Yaktocat](https://i.niupic.com/images/2020/11/03/8WN9.png)

**Comment by mouse0232** [comment]
我原本想自己测试一下是不是我自己设置的有问题。然后去找相关接口自己测试。
https://console.cloud.tencent.com/api/explorer?Product=cos 这个网址下面根本没有找到关于自定义CDN接口查询的请求API。

**Comment by Wonder233** [comment]
是否可以提工单过来，可能需要提供一下客户端日志来做进一步的排查。
https://console.cloud.tencent.com/workorder/category

**Comment by mouse0232** [comment]
> 是否可以提工单过来，可能需要提供一下客户端日志来做进一步的排查。
> https://console.cloud.tencent.com/workorder/category

我已经递交工单，并附上客户端日志。
https://console.cloud.tencent.com/workorder/detail?ticketId=202011041373

**Comment by Wonder233** [comment]
感谢反馈。
该功能确实存在问题，将在 2.4.2 版本进行修复。

**Comment by Wonder233** [comment]
您好，2.4.2 版本已发布，查看域名显示 CDN 状态不正确的问题已进行修复。

**Comment by mouse0232** [comment]
> 您好，2.4.2 版本已发布，查看域名显示 CDN 状态不正确的问题已进行修复。

已经升级到最新版，还是有问题。跟之前图片以上 未显示cdn状态。

**Comment by mouse0232** [comment]
> 您好，2.4.2 版本已发布，查看域名显示 CDN 状态不正确的问题已进行修复。

已创建最新工单，并上传最新本地客户端日志
https://console.cloud.tencent.com/workorder/detail?ticketId=202011135564

**Comment by Wonder233** [comment]
您好，已发布 2.4.3 版本，修复查看域名不兼容 V4 域名问题。
