### ISSUE TITLE
Mac客户端在排序后无法正确重命名文件

### ISSUE THREAD

**Issue by yuercl** [tencentyun/cosbrowser#134]
![image](https://user-images.githubusercontent.com/2859382/98762154-fd70bc80-2411-11eb-93d4-f355ef41b3b4.png)
![image](https://user-images.githubusercontent.com/2859382/98762169-06fa2480-2412-11eb-858f-ed0c1886b7ef.png)

**Comment by Wonder233** [comment]
您好，请问您使用的 COSBrowser 是哪个版本？COSBrowser 2.4.3已对该问题进行了修复~

**Comment by yuercl** [comment]
现在本地的版本是，v 2.4.3，不太清楚当时11.11的版本是不是v 2.4.3了。
