### ISSUE TITLE
应用内不能更新

### ISSUE THREAD

**Issue by Codename404** [tencentyun/cosbrowser#138]
应用内点击更新至2.5.1时闪退，并且应用无法卸载
![微信截图_20210104141939](https://user-images.githubusercontent.com/71927196/103506536-cf0bce00-4e11-11eb-88f8-a8642f05fa06.png)

**Comment by carsonxu** [comment]
更新前是什么版本号？

**Comment by Codename404** [comment]
> 更新前是什么版本号？

2.4.2

**Comment by Wonder233** [comment]
您好，我们测试了 2.4.2 升级至 2.5.1 版本，是没有问题的。
可能原因是在点击更新下载的安装包被电脑内的某些应用脚本修改导致安装包损坏。
您可以试试去 C:\Users\Administrator\AppData\Local\cosbrowser-updater\pending 这个文件夹下删除下载的安装包再重新点击更新或去官网直接下载最新版本进行安装。

**Comment by Codename404** [comment]
> 您好，我们测试了2.4.2升级至2.5.1版本，是没有问题的。
> 出现这个报错的可能原因是：在点击更新下载的安装包被电脑内部的某些应用脚本修改导致安装包损坏。
> 您可以尝试去C：\ Users \ Administrator \ AppData \ Local \ cosbrowser-updater \ pending这个文件夹下删除下载的安装包再重新点击更新或去官网直接下载最新版本进行安装。

好的。顺便问一下我卸载不了软件是什么原因？

**Comment by Tencent-Alice** [comment]
这边在官网下载对应的安装文件重新安装下：
https://cloud.tencent.com/document/product/436/11366 
卸载的话，这边在控制面板卸载测试下
如果还是有问题，辛苦反馈一下您的本地客户端信息
