### ISSUE TITLE
怎么支持 include

### ISSUE THREAD

**Issue by Klaus370** [tencentyun/cosbrowser#140]

**Comment by carsonxu** [comment]
什么意思？

**Comment by Klaus370** [comment]
我想问 腾讯服务器 怎么设置 支持 html 公共文件
include



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: carsonxu <notifications@github.com&gt;
发送时间: 2021年1月8日 19:06
收件人: tencentyun/cosbrowser <cosbrowser@noreply.github.com&gt;
抄送: Klaus <523824177@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[tencentyun/cosbrowser] 怎么支持 include (#140)





 
什么意思？

**Comment by Wonder233** [comment]
该问题与 COSBrowser 无关，在此先进行关闭处理。
