### ISSUE TITLE
增加文件夹同步功能

### ISSUE THREAD

**Issue by foxgst** [tencentyun/cosbrowser#142]
有一些工作素材文件比较大，比较多。
通过文件夹自动同步，可以大大提高工作效率。

**Comment by carsonxu** [comment]
![image](https://user-images.githubusercontent.com/24862812/109109084-a64be900-776f-11eb-92b3-c31364a3bf48.png)
这里有个文件夹同步的功能

**Comment by foxgst** [comment]
感谢，文档中没有看到 ～
