### ISSUE TITLE
希望对MacOS的客户端添加图片缩略图

### ISSUE THREAD

**Issue by StevenPotter** [tencentyun/cosbrowser#143]
做图床使用，没有缩略图较不方便。
![copy.png](https://img10.360buyimg.com/ddimg/jfs/t1/160299/5/13316/13135/604e4d18E92cdd327/65ed4ddcfafb19f4.png)

**Comment by Wonder233** [comment]
![image](https://user-images.githubusercontent.com/8199240/111444563-75931a00-8745-11eb-905f-8e8d022237d1.png)
您好，右键菜单里有“显示缩略图”功能哟~
