### ISSUE TITLE
希望可以提供网页及本文的在线编辑

### ISSUE THREAD

**Issue by xueleilei** [tencentyun/cosbrowser#146]
从阿里云OSS迁移过来的。发现腾讯的cosbrower 不能在线编辑一些网页等文本文件。阿里云OSSBrower 可以，请参照。在线编辑这个功能使用起来会很方便。

**Comment by carsonxu** [comment]
支持的，鼠标对文件右键，选编辑

**Comment by xueleilei** [comment]
已找到。感谢。

**Comment by carsonxu** [comment]
https://cosbrowser.cloud.tencent.com/editor
@xueleilei Web 端有编辑器模式，如果有需要可以用。
