### ISSUE TITLE
子用户登陆某个存储桶之后，菜单栏是英文的

### ISSUE THREAD

**Issue by cl-Rainful** [tencentyun/cosbrowser#147]

**Comment by Wonder233** [comment]
您好，请问您是使用的 COSBrowser 哪个版本？

**Comment by cl-Rainful** [comment]
您好，刚才登陆上去看了一下，正好有版本更新，菜单栏英文这个Bug已经没有了


请问贵公司在腾讯云运营这方面有招聘岗位吗？我非常喜欢云服务这方面的服务，自己目前有在用阿里腾讯华为等一系列对象存储服务，而且自己经常会用一些linux方面的服务，接触云服务器非常多，所以希望能有一天能够致力于这方面的工作，谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "tencentyun/cosbrowser"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月12日(星期一) 上午10:37
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [tencentyun/cosbrowser] 子用户登陆某个存储桶之后，菜单栏是英文的 (#147)





 
您好，请问您是使用的 COSBrowser 哪个版本？

**Comment by carsonxu** [comment]
感谢反馈，这里有一些岗位，可以投递简历：
https://careers.tencent.com/search.html?query=ci_1,bg_29294,at_1,ot_40001003&keyword=%E8%85%BE%E8%AE%AF%E4%BA%91

**Comment by cl-Rainful** [comment]
好的，谢谢您




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "tencentyun/cosbrowser"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月13日(星期二) 中午12:27
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [tencentyun/cosbrowser] 子用户登陆某个存储桶之后，菜单栏是英文的 (#147)





 
感谢反馈，这里有一些岗位，可以投递简历：
 https://careers.tencent.com/search.html?query=ci_1,bg_29294,at_1,ot_40001003&amp;keyword=%E8%85%BE%E8%AE%AF%E4%BA%91
