### ISSUE TITLE
文件并发数

### ISSUE THREAD

**Issue by goon7203233** [tencentyun/cosbrowser#148]
设置内的上传并发数修改保存后，再打开没有生效还是显示默认值
![image](https://user-images.githubusercontent.com/23325774/114137216-7121e180-993e-11eb-8d4b-194b7a526afd.png)

**Comment by Wonder233** [comment]
感谢反馈，确实存在这个问题，我们将在下一个版本进行修复。

**Comment by Wonder233** [comment]
版本 2.6.4 已修复该问题，谢谢您的反馈~
