### ISSUE TITLE
上传状态显示不正确！

### ISSUE THREAD

**Issue by zhouciming** [tencentyun/cosbrowser#15]
mac os x10.12.6, 上传目录时，文件和目录都上传成功了，但是上传列表里的状态是目录失败的，真是很奇怪了。而且有些目录以数字开头的，偶尔会创建目录失败，以至于上传也失败！

希望可以改进下！

**Comment by carsonxu** [comment]
已修复，谢谢反馈

**Comment by zhouciming** [comment]
我这边还遇到一个问题，就是这个软件无法退出！！
dock栏里一直存在，很奇怪！






点这个强制退出也没用。


不知道你们的这个软件进程叫什么名字，我可以直接杀下进程！


谢谢！


原始邮件
发件人:carsonxunotifications@github.com
收件人:tencentyun/cosbrowsercosbrowser@noreply.github.com
抄送:zhoucimingzhouciming@163.com; Authorauthor@noreply.github.com
发送时间:2018年8月8日(周三) 16:37
主题:Re: [tencentyun/cosbrowser] 上传状态显示不正确！ (#15)


已修复，谢谢反馈
