### ISSUE TITLE
BUG反馈！-无法取消勾选验证https

### ISSUE THREAD

**Issue by 94kan** [tencentyun/cosbrowser#150]
具体看视频

Uploading 20210411_203023.mp4…

都勾选这两个设置，然后取消校验https，然后保存，点击关闭。接着我无论是重启客户端，每次都无法取消勾选。。。

**Comment by 94kan** [comment]
![image](https://user-images.githubusercontent.com/40489346/114304372-5fd70180-9b05-11eb-8abb-c62c353b1450.png)
视频传不上，就是我取消勾选校验https无论是重启还是关闭再打开都是默认这三个选项

**Comment by 94kan** [comment]
https://user-images.githubusercontent.com/40489346/114304434-a7f62400-9b05-11eb-88fb-2c1c8cbaf729.mp4

**Comment by Wonder233** [comment]
感谢反馈，确实存在这个问题，我们将在下一个版本进行修复。

**Comment by Wonder233** [comment]
最新版本 2.6.4 已修复该问题。
