### ISSUE TITLE
不显示文件列表

### ISSUE THREAD

**Issue by supermix** [tencentyun/cosbrowser#153]
我的cos browser 不显示文件。提示dns错误，重装了也不管用。
![image](https://user-images.githubusercontent.com/5841628/118104777-22b8a480-b40e-11eb-9b65-de096dac4d73.png)
[cosbrowser.log](https://github.com/tencentyun/cosbrowser/files/6471489/cosbrowser.log)
如果解决了，请联系我aidman@aliyun.com，谢谢

**Comment by Wonder233** [comment]
您好，应该是您将高级设置里填写了 bucket 域名模板导致的。您可以尝试将下图红框处的内容清除保存并重新登录，可以解决您的问题。
![image](https://user-images.githubusercontent.com/8199240/119436381-a6e42380-bd4e-11eb-912e-3ec503b7bb4d.png)
