### ISSUE TITLE
客户端设置个性化建议

### ISSUE THREAD

**Issue by FunJoyTech** [tencentyun/cosbrowser#155]
1. 增加复制文件链接的默认选项，例如：自定义复制链接时，每次弹出都是默认域名，以及默认开启签名，是否可以开设一个选项，允许默认使用自定义域名，以及允许不开启签名。
2. 导出文件链接，是否支持设置域名？
3. 文件同步，是否可以设置过滤列表？（其他人也有提议）
4. 客户端可否设置选项，保持登陆状态，不需要每次重启计算机后都需要重新登陆？ 

虽然都不是核心问题，也不是bug，但多少还是会有一点影响用户体验。

**Comment by Wonder233** [comment]
1. 针对第一点，可以设置该存储桶的传输管理，将下载域名设置为自定义域名，此时快速复制链接默认的就是您设置的自定义域名。
![image](https://user-images.githubusercontent.com/8199240/120194462-35293f80-c250-11eb-8e70-0b4f4773b3de.png)
入口：文件列表右键菜单或存储桶列表操作更多栏
![image](https://user-images.githubusercontent.com/8199240/120194509-45d9b580-c250-11eb-9eda-fff9db30414f.png)
![image](https://user-images.githubusercontent.com/8199240/120194557-568a2b80-c250-11eb-92c8-210cf844f514.png)

2. 导出文件链接同上，只要设置了下载域名为自定义域名，导出的链接即为您设置的域名。

3. 目前还不支持，可以考虑支持。

4. 您说的这点我们已经支持了。用永久密钥和腾讯云账号登录，重启计算机后能保持登录状态。

**Comment by FunJoyTech** [comment]
> 1. 针对第一点，可以设置该存储桶的传输管理，将下载域名设置为自定义域名，此时快速复制链接默认的就是您设置的自定义域名。
> 
> <img alt="" width="500" src="https://user-images.githubusercontent.com/8199240/120195455-65251280-c251-11eb-9b97-6886b9d54779.png">
> 
> **入口1：文件列表右键菜单**
> <img alt="" width="300" src="https://user-images.githubusercontent.com/8199240/120194509-45d9b580-c250-11eb-9eda-fff9db30414f.png">
> **入口 2：存储桶列表操作更多栏**
> <img alt="" width="300" src="https://user-images.githubusercontent.com/8199240/120194557-568a2b80-c250-11eb-92c8-210cf844f514.png">
> 
> 1. 导出文件链接同上，只要设置了下载域名为自定义域名，导出的链接即为您设置的域名。
> 2. 目前还不支持，可以考虑支持。
> 3. 您说的这点我们已经支持了。用永久密钥和腾讯云账号登录，重启计算机后能保持登录状态。

原来是我没有探索出来这些使用方式，感谢回复，辛苦了！
