### ISSUE TITLE
Windows客户端-文件定时同步不生效

### ISSUE THREAD

**Issue by Andy-Chuck** [tencentyun/cosbrowser#169]
![Pic](https://user-images.githubusercontent.com/54295429/137478682-24679dec-2257-4d75-a9c0-f052e6f7d1f8.png)
以上是CosBrowser文件同步界面和当前时间的一张截图，CosBrowser一直在前台运行，但定时同步任务并未生效。
运行环境是Windows Server 2012 R2 Standard。

**Comment by Wonder233** [comment]
您好，感谢反馈，这里我们将在下个版本修复。

**Comment by Wonder233** [comment]
最新版本 v2.8.6 已修复
