### ISSUE TITLE
文件和目录不能重命名 

### ISSUE THREAD

**Issue by rawbin-** [tencentyun/cosbrowser#171]
版本 2.8.1，2.8.2 macOS

![image](https://user-images.githubusercontent.com/8169783/138250644-b248bfd3-f2f8-4764-85a6-a5e5a379f654.png)
这个图表示接下来要咋搞？

**Comment by Wonder233** [comment]
或许因为操作系统原因应用无法自动关闭重启，您可以手动退出后重新打开应用。
