### ISSUE TITLE
同一账户，在桌面端能访问到桶，但在网页端却提示没有权限

### ISSUE THREAD

**Issue by SaiLoong** [tencentyun/cosbrowser#173]
账号：ieg_avatar_gameai (id: 100021517793)

网页端：
![image](https://user-images.githubusercontent.com/26319553/141887374-9fc8c3d6-0de5-4bae-bcb4-4d5b9eedd40f.png)

桌面端：
![image](https://user-images.githubusercontent.com/26319553/141887544-74003f7b-6f5d-475e-8968-49ab72277f4a.png)

**Comment by Wonder233** [comment]
您好，是否可以提一个工单过来研发进行分析？
https://console.cloud.tencent.com/workorder/category?level1_id=83&level2_id=84&source=0&data_title=%E5%AF%B9%E8%B1%A1%E5%AD%98%E5%82%A8%20COS&step=1
