### ISSUE TITLE
批量下载卡住

### ISSUE THREAD

**Issue by Forliove1** [tencentyun/cosbrowser#177]

**Comment by Wonder233** [comment]
您好，是否可以提一个工单过来进行分析？需要您提供客户端本地日志信息查看批量下载卡住的原因。
https://console.cloud.tencent.com/workorder/category?level1_id=83&level2_id=84&source=0&data_title=%E5%AF%B9%E8%B1%A1%E5%AD%98%E5%82%A8%20COS&step=1
