### ISSUE TITLE
Web 版本能弄一份部署包吗

### ISSUE THREAD

**Issue by netnr** [tencentyun/cosbrowser#179]

**Comment by netnr** [comment]
或者说在线上地址 https://cosbrowser.cloud.tencent.com/web/bucket 添加传密钥的方式

**Comment by Wonder233** [comment]
可以再具体描述一下，没有看懂您的需求是什么？

**Comment by netnr** [comment]
支持这种模式
https://cosbrowser.cloud.tencent.com/web/bucket?AppId=1&SecretId=2&SecretKey=3

发布出来，可以自己部署到服务器

**Comment by Wonder233** [comment]
抱歉，由于涉及一些内部逻辑，无法开源。
