### ISSUE TITLE
希望可以增加列表模式以及排序

### ISSUE THREAD

**Issue by cooper1x** [tencentyun/cosbrowser#18]
cos客户端目前都是小图标文件，希望可以添加一个列表模式，类似Windows的列表，这样就能方便看到文件名的全称了。
另外希望可以增加按日期和名称排序，这样比较方面查看哪些是最近的上传过的文件。

**Comment by carsonxu** [comment]
暂时不支持，有计划增加列表展示

**Comment by MarcelloSloan** [comment]
希望增加排序功能~

**Comment by carsonxu** [comment]
最新1.2.0版本已支持列表显示，排序不支持

**Comment by orq866** [comment]
希望支持文件大小排序。最需要的功能，不然也不用客户端
