### ISSUE TITLE
删除文件夹巨慢,无力吐槽

### ISSUE THREAD

**Issue by yi1260** [tencentyun/cosbrowser#2]

**Comment by carsonxu** [comment]
谢谢单块

**Comment by carsonxu** [comment]
谢谢反馈，这里后面优化下速度和进度反馈

**Comment by carsonxu** [comment]
谢谢反馈，这里后面优化下速度和进度反馈

**Comment by yi1260** [comment]
关键是会出现删除之后, 刷新又出现的问题

**Comment by carsonxu** [comment]
![image](https://user-images.githubusercontent.com/24862812/39293530-aff5c56e-496b-11e8-829f-f97d3569b706.png)
已修复删不了的问题，优化了删除速度和交互反馈。重新下载体验下。

**Comment by carsonxu** [comment]
如微信群沟通，已解决
