### ISSUE TITLE
文件查询的条件过滤问题

### ISSUE THREAD

**Issue by AmazingChen** [tencentyun/cosbrowser#21]
在右上角搜索框中输入查询条件，找到目标文件夹后，点击进入，该文件夹内的资源还是会被上一层文件夹的查询条件所限制，需要再次清除查询条件，再手动点一下刷新，才会显示目标文件夹下的资源列表。
不知道这个查询功能是存在bug，还是原本的设计，总感觉搜索完之后，就应该忽略查询条件，否则还需要清除查询条件（如果已经进入目标文件夹，还需要再刷新一次才会显示）。
希望能得到回馈，谢谢。

**Comment by carsonxu** [comment]
这个算一个 Bug。下一版重新整理下：
1. 搜索，出现搜索结果，点击刷新还是搜索结果，最下面的加载更多也根据搜索条件过滤
2. 进入目录、切换路径、切换 bucket 都先清除搜索条件，再显示列表。

**Comment by carsonxu** [comment]
已修复

**Comment by carsonxu** [comment]
最新1.2.0版本
