### ISSUE TITLE
能把详情中文件链接中的默认域名设置成加速域名吗？

### ISSUE THREAD

**Issue by istevenshen** [tencentyun/cosbrowser#24]
对于存储桶的图片，默认域名不支持浏览器在线预览，每次想要获取在线预览url，还要手动去把默认域名更改为加速域名：详情→文件链接→把默认域名更改为加速域名→浏览器的预览。

这么多操作步骤，体验太差了~~

**Comment by carsonxu** [comment]
双击，自动下载完会本地打开，就可以看到图片了。
如果增加 CDN 链接，需要判断是否已开启 CDN 加速，这里就要调用 COS API 以外的接口，短期暂不提供。
