### ISSUE TITLE
QQ截图 无法快速存入cos

### ISSUE THREAD

**Issue by daihainidewo** [tencentyun/cosbrowser#25]
qq截图后，在客户端复制，弹框说粘贴板为空
![](https://img-1251474779.cos.ap-beijing.myqcloud.com/ztbwk.png)

**Comment by carsonxu** [comment]
你是希望截图后，ctrl+V 直接上传截图？

**Comment by huifeng82** [comment]
> qq截图后，在客户端复制，弹框说粘贴板为空
> ![](https://camo.githubusercontent.com/ec22aa24393535a495dcab7f37051400e4daedc3/68747470733a2f2f696d672d313235313437343737392e636f732e61702d6265696a696e672e6d7971636c6f75642e636f6d2f7a7462776b2e706e67)

可以参考PicGo：https://github.com/Molunerfinn/PicGo/releases

**Comment by carsonxu** [comment]
近期支持

**Comment by carsonxu** [comment]
v1.3.4 已支持
