### ISSUE TITLE
上传中文名称会出现乱码

### ISSUE THREAD

**Issue by letxxt** [tencentyun/cosbrowser#27]
传的QQ截图命名变成了这样
![2018124401645](https://user-images.githubusercontent.com/23730422/47476579-b2e46d80-d853-11e8-9650-86f8cb3c90ad.jpg)

**Comment by carsonxu** [comment]
操作步骤给一下？是不是所有中文文件都会？

**Comment by letxxt** [comment]
就是选择了上传整个文件夹，然后就这样了，图片和压缩包都乱码了

**Comment by carsonxu** [comment]
试了我电脑没这个问题。
系统信息和 chrome 的 navigator.userAgent 信息给一下？

**Comment by carsonxu** [comment]
确认下是不是最新版本？

**Comment by letxxt** [comment]
我的错，原来是下载出问题了

**Comment by carsonxu** [comment]
ok
