### ISSUE TITLE
子账号无法添加北京一区的路径

### ISSUE THREAD

**Issue by lxysir** [tencentyun/cosbrowser#28]
![image](https://user-images.githubusercontent.com/21137043/47543176-927be800-d913-11e8-8658-e593e718dd66.png)
![image](https://user-images.githubusercontent.com/21137043/47543193-9f98d700-d913-11e8-8d01-1dbc9a714477.png)
子账号填ap-beijing-1报错路径错误，填ap-beijing显示没权限

**Comment by carsonxu** [comment]
已修复
