### ISSUE TITLE
希望可以增加复制粘贴、图片预览、随机生成上传文件名的功能

### ISSUE THREAD

**Issue by MapleGe** [tencentyun/cosbrowser#29]
如题，希望可以QQ截图之后，直接ctrl+v上传，并且可以预览图片，不然图片多了不知道哪个是刚刚上传的。

还有希望可以随机生成上传的文件名，有的时候都是1.jpg上传的，没有任何提示就直接覆盖掉原来的图片了。

**Comment by carsonxu** [comment]
已支持QQ截图粘贴

**Comment by carsonxu** [comment]
已支持缩略图
群里上传文件名，后续再统一优化。
