### ISSUE TITLE
是否可提供一个MAC版本

### ISSUE THREAD

**Issue by mrtylerwang** [tencentyun/cosbrowser#3]
是否可提供一个MAC版本

**Comment by carsonxu** [comment]
技术上可以的，需要时间修改兼容问题

**Comment by fateleak** [comment]
+1 同求

**Comment by carsonxu** [comment]
@mrtylerwang @fateleak MAC 版本已处理完兼容问题，欢迎体验预览版找 bug：
https://cos5.cloud.tencent.com/cosbrowser/releases/cosbrowser-latest.dmg

**Comment by carsonxu** [comment]
已发布 macOS 版
