### ISSUE TITLE
[Feature Request] 遇到重复文件可选择“跳过”或“替换”

### ISSUE THREAD

**Issue by firede** [tencentyun/cosbrowser#31]
在批量上传的场景中，遇到重复文件希望能够弹出“跳过”或“替换”的选项，比如：

> 遇到 42 个同名文件，你想要：
>
> <kbd>替换这些文件</kbd> <kbd>跳过这些文件</kbd> <kbd>让我决定每个文件</kbd>

或者：

> 文件 “foo” 已经存在，你想要：
>
> ☑️本次操作不再询问我，采用相同策略
> <kbd>替换文件</kbd> <kbd>跳过文件</kbd>

**Comment by carsonxu** [comment]
谢谢建议，后续会具体优化，至少会增加设置项。

**Comment by carsonxu** [comment]
在“高级上传”已支持选择：覆盖、跳过、重命名
