### ISSUE TITLE
出现无法图片文件上传错误

### ISSUE THREAD

**Issue by kinredon** [tencentyun/cosbrowser#32]
![image](https://user-images.githubusercontent.com/39270545/48904588-d3770600-ee99-11e8-968f-ecdf25936ff4.png)

**Comment by carsonxu** [comment]
是网络错误，确认下网络是否正常，有没有配置了 IE 代理？

**Comment by carsonxu** [comment]
cosbrowser 下载不带有 referer header。
使用了防盗链白名单，暂不支持 cosbrowser 下载，
需要 COS API 更新 防盗链 判断逻辑，或 cosbrowser 提供下载 referer 设置。

**Comment by kinredon** [comment]
嗯，我配置了防盗链。谢谢了：）
