### ISSUE TITLE
MWeb能支持吗？

### ISSUE THREAD

**Issue by nlpjoe** [tencentyun/cosbrowser#34]
如题

**Comment by carsonxu** [comment]
会考虑简单文本编辑，需要产品具体确认具体实现程度。
cosbrowser 核心功能是文件管理，不做复杂的边缘功能。

**Comment by nlpjoe** [comment]
就是七牛云那种能直接上传图片到图床的。实在不行也把cosbrowser弄个按时间排序鸭，不然找个上传的东西眼睛都找瞎了




    



    
    
    



    
        
            
                
                    
                        
                    
                    
                        
                            joezhow777
                            
                            
                                
                                    邮箱：joezhow777@gmail.com
                                
                        
                    
                
            
        
    


Signature is customized by Netease Mail Master


在2018年12月13日 22:44，carsonxu 写道： 会考虑简单文本编辑，需要产品具体确认具体实现程度。
cosbrowser 核心功能是文件管理，不做复杂的边缘功能。

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/tencentyun/cosbrowser","title":"tencentyun/cosbrowser","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/tencentyun/cosbrowser"}},"updates":{"snippets":[{"icon":"PERSON","message":"@carsonxu in #34: 会考虑简单文本编辑，需要产品具体确认具体实现程度。\r\ncosbrowser 核心功能是文件管理，不做复杂的边缘功能。"}],"action":{"name":"View Issue","url":"https://github.com/tencentyun/cosbrowser/issues/34#issuecomment-446992792"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/tencentyun/cosbrowser/issues/34#issuecomment-446992792",
"url": "https://github.com/tencentyun/cosbrowser/issues/34#issuecomment-446992792",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by carsonxu** [comment]
排序需要GetBucket列出目录下所有文件才能在客户端排序，近期增加支持，点击排序加载完整列表再排序。
