### ISSUE TITLE
最新版 直接拖动目录上传,会产生0字节的与子目录相同的文件

### ISSUE THREAD

**Issue by clbi88** [tencentyun/cosbrowser#44]
最新版 直接拖动目录上传,会产生0字节的与子目录相同的文件

**Comment by carsonxu** [comment]
这个是正常表现，对象存储里没有文件夹的概念，只能是用一个 / 结尾空文件作为占位表示有这个目录。
这里这么处理可以避免上传的时候空目录，在 cosbrowser 没有对应的“文件夹”。

**Comment by Huangzhecheng** [comment]
最新版 直接拖动目录上传,会产生0字节的与子目录相同的文件

上一版本没有这样的问题

**Comment by carsonxu** [comment]
产生的是文件还是文件夹？

**Comment by carsonxu** [comment]
确认了一下，是 bug，今晚修复

**Comment by Huangzhecheng** [comment]
> 
> 
> 确认了一下，是 bug，今晚修复
十分感谢

**Comment by carsonxu** [comment]
@clbi88 @Huangzhecheng 已修复，请重新下载最新版本
