### ISSUE TITLE
客户端替换一个图片，线上环境用的图片没有变化

### ISSUE THREAD

**Issue by fairyly** [tencentyun/cosbrowser#47]
客户端替换一个图片，线上环境用的图片没有变化，还是原来的图片（已清缓存）

**Comment by carsonxu** [comment]
如果工具提示上传成功，不应该出现这个问题，可以把链接贴上确认下原因。
或者在腾讯云提交工单排查。

**Comment by fairyly** [comment]
> 如果工具提示上传成功，不应该出现这个问题，可以把链接贴上确认下原因。
> 或者在腾讯云提交工单排查。
```
web：http://web-1251519181.file.myqcloud.com/components/logo.png
客户端： https://web-1251519181.cos.ap-shanghai.myqcloud.com/components/logo.png
```

客户端 复制地址 和 线上的地址是不一样的

**Comment by carsonxu** [comment]
.file. 是是 CDN 域名，你需要把链接放到 CDN 控制台刷新 CDN 缓存

**Comment by fairyly** [comment]
> .file. 是是 CDN 域名，你需要把链接放到 CDN 控制台刷新 CDN 缓存

感谢了
