### ISSUE TITLE
建议：显示文件数、显示选中文件数

### ISSUE THREAD

**Issue by BreezeFreak** [tencentyun/cosbrowser#51]
在比对文件夹是否如数复制的时候，遇到如题的需求。辛苦了！希望能有所帮助

**Comment by carsonxu** [comment]
谢谢建议，当前复制任务只有一个冒泡位置较少，可以加“显示文件数”

**Comment by carsonxu** [comment]
![image](https://user-images.githubusercontent.com/24862812/57842321-d1fe1900-77fe-11e9-9721-1535bd07ca28.png)
已增加文件数
