### ISSUE TITLE
希望添加小图显示开关

### ISSUE THREAD

**Issue by bloodspasm** [tencentyun/cosbrowser#52]
<img width="779" alt="屏幕快照 2019-05-24 下午3 04 50" src="https://user-images.githubusercontent.com/10420472/58308887-4d7e4c80-7e35-11e9-9124-9003a6c0d077.png">
这种情况我都不知道图片显示长什么样,需要一个一个打开预览.

**Comment by carsonxu** [comment]
右键有个显示缩略图，试用下。

**Comment by bloodspasm** [comment]
可以使用
