### ISSUE TITLE
能不能加个按时间和大小排序功能

### ISSUE THREAD

**Issue by coder2018cp** [tencentyun/cosbrowser#56]
如题， 现在文件多了十分不方便，只能根据前缀，而实际上希望能根据修改时间来排序。由于搜索只能根据文件名前缀来搜，十分不便捷，希望能考虑增加按时间排序功能，或者增强一下搜索功能，支持模糊搜索。感谢！！！

**Comment by Wonder233** [comment]
您好，COSBrowser 最新版本 2.4.3 已支持模糊搜索以及允许按时间或文件大小进行排序，感谢反馈~
