### ISSUE TITLE
新功能建议

### ISSUE THREAD

**Issue by LittleFatHero** [tencentyun/cosbrowser#57]
1.首先在cosbrowser里面新建文件夹，不能设置文件夹的权限，这个就很难受，建议增加设置新建文件夹权限的功能
2.上传的图片看不到图片的样子，能不能实现能够看到图片的样子
3.文件名稍微长一点，就看不到文件全名了，只有一个视图可选
4.不好意思，问题太多，卸载了直接，，，，

**Comment by carsonxu** [comment]
感谢建议，我们会持续优化体验。
1. 文件夹权限、存储桶权限后续会补上，之前的定位是先做好基本的文件管理，还没开始实现文件夹权限操
作。
2. 上传的图片要显示缩略图，右键显示缩略图就会显示，当前显示会拉取原图产生流量，所以暂不默认显示缩略图。
3. 支持列表和宫格两种视图，如下图按钮：
![image](https://user-images.githubusercontent.com/24862812/60811265-75e1c080-a1c1-11e9-9102-45dda253120f.png)

**Comment by LittleFatHero** [comment]
> 感谢建议，我们会持续优化体验。
> 
> 1. 文件夹权限、存储桶权限后续会补上，之前的定位是先做好基本的文件管理，还没开始实现文件夹权限操
>    作。
> 2. 上传的图片要显示缩略图，右键显示缩略图就会显示，当前显示会拉取原图产生流量，所以暂不默认显示缩略图。
> 3. 支持列表和宫格两种视图，如下图按钮：
>    ![image](https://user-images.githubusercontent.com/24862812/60811265-75e1c080-a1c1-11e9-9102-45dda253120f.png)

还有，好像没有办法复制图片的存储地址，只能复制临时地址，这个怎么破？

**Comment by carsonxu** [comment]
当前版本有两个地方：
1. 右键文件复制链接，默认15分钟。
2. 右键文件详情，私有读的文件会有一个复制图标和笔的图标，点击笔图标弹出选时间弹窗。如下图：

由于当前版本指定时间复制链接不明显，下个版本：
1. 改成右键“复制链接”，直接弹窗选时间复制。
2. 默认时间改更久一些。

![image](https://user-images.githubusercontent.com/24862812/60812198-8a26bd00-a1c3-11e9-9217-cd03faec9535.png)
![image](https://user-images.githubusercontent.com/24862812/60812276-b8a49800-a1c3-11e9-8a84-a836539332a4.png)

**Comment by idoshe** [comment]
建议上传的文件，可以增加**最新上传排序功能**，文件太多，找起来太麻烦了哦

**Comment by github65535** [comment]
建议增加 文件夹备注功能（可能需要配套搜索备注功能），操作的人多了交接成本也越来越大😓
期待

**Comment by carsonxu** [comment]
@github65535 谢谢建议，短期内暂不支持，可以先大家约定一下，在目录下放一个 README.md 或者直接写个文件名比如 “备注_存放图片_carsonxu.txt”

**Comment by carsonxu** [comment]
再次 review 这里需求点：
1. 上传排序，这里跟进：https://github.com/tencentyun/cosbrowser/issues/56
2. 文件夹授权，已在排期中
3. 文件夹备注，暂不支持。
先关单。
