### ISSUE TITLE
客户端更新后，复制的链接变为临时链接。

### ISSUE THREAD

**Issue by kinredon** [tencentyun/cosbrowser#59]
![image](https://user-images.githubusercontent.com/39270545/61037486-c04f8100-a3fd-11e9-8e92-dfd5e430b8f9.png)
更新后，上图复制链接变为了临时链接，无法成功访问。

**Comment by carsonxu** [comment]
谢谢反馈我们尽快修复，可以先用右键复制链接

**Comment by kinredon** [comment]
谢谢，右键复制链接成功。
