### ISSUE TITLE
使用反馈

### ISSUE THREAD

**Issue by Janet-Baker** [tencentyun/cosbrowser#60]
初次体验，有几个比较明显的问题：
- 1.启动时，切换界面或者最小化后重新打开，会有一段时间的绘图延迟（会有一个黑色的框）。
- 2.打开“上传列表”后，双击左上角可以使文件列表最大化，然后上传列表窗口也跟着跑了。
- 3.不支持后台驻留，关掉窗口就停止工作了。
- 4.Windows版找不到管理存储桶的入口。
- 5.应用程序内没有通往网页版控制台的入口。可以做的隐蔽一些但不能没有啊。
- 6.文件列表不能按大小、修改时间排序

**Comment by carsonxu** [comment]
感谢建议！
1由于基于electron暂时没找到好的解决方法。
3/5/6已有计划修改，其中排序只能列完所有文件才能排序。
2/4我们确认下近期优化。

**Comment by carsonxu** [comment]
v2.0.1优化：
1/3. 短期不支持
2. 上传交互已更改
4. 提供列存储桶列表以及对应操作，可以添加、删除、修改存储桶权限
5. 下个小版本加上。
6. 排序这里跟进 https://github.com/tencentyun/cosbrowser/issues/56
先关单。
