### ISSUE TITLE
共有读不要添加签名

### ISSUE THREAD

**Issue by yaoxingshuai** [tencentyun/cosbrowser#61]
共有读的文件，之前点击链接是没有 sign的， 更新版本后多了sign， 这个是不需要的
![图片](https://user-images.githubusercontent.com/16911333/61207680-5221fb80-a728-11e9-8acc-611b1a6547d6.png)

**Comment by carsonxu** [comment]
先用右键复制链接，近期修正

**Comment by carsonxu** [comment]
v1.4.1已修复
