### ISSUE TITLE
往小程序云开发的储存桶里上传的文件,小程序里不可以通过fileID读取

### ISSUE THREAD

**Issue by sammychiang** [tencentyun/cosbrowser#63]

**Comment by carsonxu** [comment]
是调用哪个接口传 fileID？

**Comment by sammychiang** [comment]
用小程序控制台的云储存上传的每个文件会自动生成一个fileID, 就是 "cloud://<环境值>/<路径>", 在小程序端可以直接通过fileID来读取文件,但是用cosbrowser上传的文件,通过这个规则用fileID去读取,就会失败

**Comment by sammychiang** [comment]
> 是调用哪个接口传 fileID？

用小程序控制台的云储存上传的每个文件会自动生成一个fileID, 就是 "cloud://<环境值>/<路径>", 在小程序端可以直接通过fileID来读取文件,但是用cosbrowser上传的文件,通过这个规则用fileID去读取,就会失败

**Comment by carsonxu** [comment]
在小程序云上传的文件是先走他们逻辑，再传 COS API。
cosbrowser 上传的文件是直接调用 COS 的 API，在小程序云没存id记录，涉及权限相关的东西，会读取不到。建议只在小程序云操作存储桶。

**Comment by sammychiang** [comment]
好, 就是小程序控制台上传文件太慢, 并且总是卡住,我才用了cosbrowser

**Comment by sammychiang** [comment]
找到一个解决方案了 https://github.com/TencentCloudBase/tcb-admin-node/blob/master/docs/storage.md#%E4%B8%8A%E4%BC%A0%E6%96%87%E4%BB%B6
