### ISSUE TITLE
启动后10秒左右闪退

### ISSUE THREAD

**Issue by clinmanc** [tencentyun/cosbrowser#64]
![image](https://user-images.githubusercontent.com/10267779/61526382-e5bb3b00-aa4c-11e9-8ab2-36dd4448930e.png)
最新日志
系统 Win 10, 版本1.4.0

**Comment by clinmanc** [comment]
Win 10, 1.4.0

**Comment by carsonxu** [comment]
v1.4.1加了崩溃上报，可否重试新版本

**Comment by clinmanc** [comment]
最近没有崩溃了，包括1.4.0版本
