### ISSUE TITLE
对腾讯云COSBrowser的几点特性改进

### ISSUE THREAD

**Issue by chenfanyue** [tencentyun/cosbrowser#66]
https://chenfanyue.cn/several-feature-improvements-regarding-tencent-cloud-cosbrowser/

**Comment by carsonxu** [comment]
感谢建议。
1. 创建多级目录，已修改，下次更新支持
2. 载入链接到 COS，有考虑过可能作为一个附带小工具提供
3. 小红点暂不修改
4. Bucket 级别的操作，后面几个版本支持
5. 反馈系统暂时能用，移动端使用的时 tucao.qq.com，有可能会统一到 tucao，暂不考虑在客户端直接填写

**Comment by carsonxu** [comment]
v1.4.1已支持创建多层文件夹

**Comment by chenfanyue** [comment]
在单击新建文件夹后，建议文本输入框**自动捕获焦点**

另，为什么文件可以rename，但文件夹不可以rename？我不清楚服务端object storage的实现代码，我的猜测是
> 在对象存储里没有文件，文件夹之分，一切皆是对象。
标志对象的唯一决定因素应该是一个唯一的hash string，其它的像name，priviledge
什么的皆是次要属性，都可以修改。
对象之间的关联应该也只是一个普通属性。

如果以上猜测正确，那从用户的角度讲，一切皆可以rename，皆可以**合理地移动位置**。

**Comment by carsonxu** [comment]
@chenfanyue 重命名文件夹需要对下面所有文件的路径，进行重命名。
这里较复杂，还没支持，可以先手动创建新文件夹，然后复制过去，自行确认好再删除老的。
后面版本会支持重命名文件夹。

**Comment by carsonxu** [comment]
v2.0.1 已完成：
1. 重命名鼠标聚焦
2. 载入链接到 COS，在上传时可以添加 url 任务
3. Bucket 级别的操作，可以查看存储桶详情、设置存储类型、权限、删除和创建。

未完成
重命名文件夹，考虑后面支持。

这里先关单
