### ISSUE TITLE
建议增加上传前时间戳重命名功能

### ISSUE THREAD

**Issue by cloudshadow7** [tencentyun/cosbrowser#67]
命名规则：时间戳+文件名；
譬如a.jpg 上传后名字 20190728220000_a.jpg
PC客户端现在没有办法排序，文件搜索功能也比较弱，只能搜前缀，重命名后就可以按上传日期时间搜索了

**Comment by carsonxu** [comment]
“高级上传”弹窗里支持上传，遇到已存在重命名。
文件搜索已支持模糊搜索。
