### ISSUE TITLE
希望增加文件列表文件数统计

### ISSUE THREAD

**Issue by zhangyulai** [tencentyun/cosbrowser#69]
希望能够显示某一个文件夹下的文件总个数

**Comment by carsonxu** [comment]
下个版本在存储桶详情里加上。

**Comment by Wonder233** [comment]
您好，最新版本 COSBrowser 支持在存储桶列表操作栏查看【统计】，可以看到存储桶的存储用量及对象数量。
文件夹总数目前没有支持计划。
