### ISSUE TITLE
下载大量文件会假死

### ISSUE THREAD

**Issue by march1993** [tencentyun/cosbrowser#70]
下载数万的文件时界面会假死

![微信截图_20190816120207](https://user-images.githubusercontent.com/5122675/63142766-b54fc800-c01d-11e9-8af2-a4f291e22826.png)

**Comment by march1993** [comment]
Linux 平台没有这个问题，似乎是 Windows 平台独有的问题

**Comment by carsonxu** [comment]
试试最新版本 v2.5.0
