### ISSUE TITLE
正确输入SecretId和SecretKey提示我SecretId填写错误

### ISSUE THREAD

**Issue by Mrx1e** [tencentyun/cosbrowser#73]
![image](https://user-images.githubusercontent.com/30990680/63255990-44bcdb80-c2a9-11e9-83ad-f5c8beb77092.png)

新建了多个SecretId每次都是直接点击复制按钮进行粘贴，全部SecretId都出现这个报错

**Comment by carsonxu** [comment]
这个是真的输错了，或者是填写了 Service域名/Bucket域名且对不上。
