### ISSUE TITLE
存储桶显示其他appid的数据

### ISSUE THREAD

**Issue by catbb2018** [tencentyun/cosbrowser#74]
SecretID,SecretKey与其他存储不一样的情况下，登录后存储桶左边列可看到其他appid下的项目，是哪里关联出的问题
![QQ截图20190911153849](https://user-images.githubusercontent.com/36918583/64677523-4f365380-d4aa-11e9-8f6e-86e392868279.png)

**Comment by carsonxu** [comment]
子帐号如果有权限，可以看到主张号的存储桶列表。
确认下是否用了某个主张号下的子帐号密钥？

**Comment by catbb2018** [comment]
> 子帐号如果有权限，可以看到主张号的存储桶列表。
> 确认下是否用了某个主张号下的子帐号密钥？

3Q，我跟技术反馈下让他们检查下相关权限
