### ISSUE TITLE
状态码 402 Payment Required

### ISSUE THREAD

**Issue by shuiyihan12** [tencentyun/cosbrowser#76]
windows cosbrowser v1.4.5   下载图片   

状态码 402 Payment Required

![2019-10-08_13-02-18](https://user-images.githubusercontent.com/34962990/66368804-4e6edf80-e9cc-11e9-9df7-ca05e4c40b1d.jpg)

**Comment by carsonxu** [comment]
确认下是否以下两种情况：
1. 欠费请续费。
2. 小程序云创建的存储桶，不支持再 cosbrowser 下载。
