### ISSUE TITLE
选中错误的文件

### ISSUE THREAD

**Issue by zhouii** [tencentyun/cosbrowser#77]
当文件量比较大时，拉到下面对靠后的文件点击最右边的删除按钮，复选框会选在它的上一个文件，如果确认删除的话删的也是上一个文件。如果点击复制链接的按钮，复选框也会选在它的上一个文件并且复制的是上一个文件的链接（已是v1.4.5最新版）

**Comment by carsonxu** [comment]
下个版本修复，当前可以先用右键删除文件。

**Comment by carsonxu** [comment]
已修复
