### ISSUE TITLE
上传文件夹，里面文件内容被修改

### ISSUE THREAD

**Issue by lovelyjpw** [tencentyun/cosbrowser#79]
将文件夹拖入COSBrower客户端后，然后从客户端下载某一文件，发现内容跟原文件不一样
<img width="1120" alt="QQ20191118-122231@2x" src="https://user-images.githubusercontent.com/5998439/69024544-2d9f9e00-09fe-11ea-8fe5-e3ca4bdb2933.png">

**Comment by carsonxu** [comment]
上传过程不处理内容。只可能是在别的地方有修改导致。
