### ISSUE TITLE
搜索框目录搜索问题

### ISSUE THREAD

**Issue by catbb2018** [tencentyun/cosbrowser#80]
版本 v1.5.1 的搜索框是不是有点问题 打开几级目录后进行对文件夹名称模糊查询  遍历的竟然不是当前目录下的目录名称 而是会遍历所有文件
![QQ图片20191119181041](https://user-images.githubusercontent.com/36918583/69137552-f4e3ef80-0af7-11ea-83cc-6716ed2b8328.png)

**Comment by carsonxu** [comment]
搜索框更改了逻辑：
1. 以前是前缀搜索后端接口支持的，会很快
2. 更改后，是遍历整个存储桶，支持模糊搜索
这里下个版本会把前缀搜索加回去，加一个选项选择“前缀搜索”或“模糊搜索”

**Comment by carsonxu** [comment]
v1.5.3已支持
