### ISSUE TITLE
获取桌面版sha512

### ISSUE THREAD

**Issue by MeowCold** [tencentyun/cosbrowser#81]
如何获取桌面版的sha512

**Comment by carsonxu** [comment]
https://cos5.cloud.tencent.com/cosbrowser/releases/latest.yml

**Comment by MeowCold** [comment]
怎么跟我校验值不一样
2aec0ed54297c432b9f70b6b744d254191f2495bc0c82a9b725ed31a4f6775d27e27a4f13de50b386fe532938ac889142bcea0251b513e448d5d238ed2722d40

**Comment by carsonxu** [comment]
下载最新版本应该是一样，你的版本会不会是老的版本？
