### ISSUE TITLE
COSBrowser PC 端能设置在后台运行吗？

### ISSUE THREAD

**Issue by shenweiyan** [tencentyun/cosbrowser#83]
v-1.5.3 增加了本地文件夹同步的功能，我想把 COSBrowser 设置一直在后台运行并自动同步，需要怎么设置？谢谢。

**Comment by carsonxu** [comment]
当前需要最小化到任务栏，暂时没支持最小化到托盘。后续会补充支持。

**Comment by carsonxu** [comment]
https://github.com/tencentyun/cosbrowser/issues/83

**Comment by Wonder233** [comment]
已支持。
