### ISSUE TITLE
手机端的 COSBrowser 下载图片后，无法在系统相册中找到

### ISSUE THREAD

**Issue by shenweiyan** [tencentyun/cosbrowser#84]
从 cos bucket 中下载了一张图片，想要通过微信把它发给朋友时，发现在打开微信选择照片时却无法找到新下载的图片。同样在打开的 Android 系统相册中也完全找不到这个照片，虽然这个图片确确实实已经下载到了手机上。

手机系统： Adnroid EMUI 9.1.0

**Comment by konakonall** [comment]
我们下一个版本优化下

**Comment by rickenwang** [comment]
已经修复了
