### ISSUE TITLE
点击bucket list查看文件的时候，报错 ERR_TLS_CERT_ALTNAME_INVALID

### ISSUE THREAD

**Issue by VictoryDong** [tencentyun/cosbrowser#85]
![image](https://user-images.githubusercontent.com/11418609/70764150-97a72b00-1d91-11ea-9c24-d6fea79de269.png)

**Comment by carsonxu** [comment]
请检查 Bucket域名是否多写了配置了 service.

**Comment by VictoryDong** [comment]
{Bucket}-的短线写成了.导致的。感谢
