### ISSUE TITLE
拖动滚动条后会错误选中一些文件

### ISSUE THREAD

**Issue by zhouii** [tencentyun/cosbrowser#89]
在文件列表拖动滚动条，如果鼠标在滚动条左侧放开，就会去选中一些文件，这不应该发生。

另外，滚动条太细了，建议像Windows系统滚动条那样粗细使用起来更舒服。而且都已经这么细了，似乎还只有左边一半能用，当鼠标在滚动条右边一半时就是控制窗口大小的箭头了

**Comment by carsonxu** [comment]
拖滚动条会取消选中的问题，下个版本已修复。
太细问题，我们讨论下。谢谢建议。

**Comment by carsonxu** [comment]
2.0.0 已修复
