### ISSUE TITLE
在预览模式浏览图片，链接地址有问题。

### ISSUE THREAD

**Issue by northwolfwu** [tencentyun/cosbrowser#90]
[https://pic-1251602985.cos.ap-shanghai.myqcloud.com/issue/cos-2020-01-25_172232.jpg](url)
点击复制链接，第一张图片链接正确，但是如果点击左右箭头浏览另外的图片，链接有问题，一直都是第一张图片的链接。

**Comment by carsonxu** [comment]
感谢反馈，下个版本修复。

**Comment by carsonxu** [comment]
v2.0.1 fixed
