### ISSUE TITLE
登陆一直在正在加载页面循环不能进去

### ISSUE THREAD

**Issue by ebhorizon** [tencentyun/cosbrowser#91]
2020-02-08还可以正常使用
2020-02-09就无法正常使用 打开登陆的时候停在了正在加载页面 小圈圈无限循环地旋转转到发慌
![image](https://user-images.githubusercontent.com/49278546/74098432-05ce5b00-4b53-11ea-93cc-42df5d7a3cda.png)

**Comment by carsonxu** [comment]
请提交一个工单到腾讯云，附上日志文件。

**Comment by ebhorizon** [comment]
问题刚刚解决了 关闭了https 虽然不知道为什么这样就可以了

发送自 Windows 10 版邮件应用

发件人: carsonxu
发送时间: 2020年2月9日 16:36
收件人: tencentyun/cosbrowser
抄送: ebhorizon; Author
主题: Re: [tencentyun/cosbrowser] 登陆一直在正在加载页面循环不能进去 (#91)

请提交一个工单到腾讯云，附上日志文件。

**Comment by carsonxu** [comment]
有可能是开了一些代理软件。

**Comment by ebhorizon** [comment]
你好， 发现的问题是， 打开优酷客户端之后， 腾讯系列产品普遍会有打不开的现象， 关闭优酷后一部分比如qq邮箱和qq正常， 但是cosbrowser客户端会不支持ssl， cos网页端正常。

发送自 Windows 10 版邮件应用

发件人: carsonxu
发送时间: 2020年2月10日 14:37
收件人: tencentyun/cosbrowser
抄送: ebhorizon; Author
主题: Re: [tencentyun/cosbrowser] 登陆一直在正在加载页面循环不能进去 (#91)

有可能是开了一些代理软件。

**Comment by carsonxu** [comment]
暂判断是网络问题，先结单。
