### ISSUE TITLE
Mac使用的时候偶尔会闪退

### ISSUE THREAD

**Issue by chenchunyang12345** [tencentyun/cosbrowser#93]
1、删除文件夹中文件时
2、刷新操作

**Comment by carsonxu** [comment]
这个是已知问题，暂时没有定位到原因。
后面的版本尝试更新 electron 版本，看是否能修复闪退。

**Comment by carsonxu** [comment]
闪退是 electron 老版本的 bug，v2.4.0 版本已更新了 electron 版本，如果还有问题可以再反馈。
