### ISSUE TITLE
复制大量文件时会卡住不动.

### ISSUE THREAD

**Issue by codemonkey-m** [tencentyun/cosbrowser#94]
![image](https://user-images.githubusercontent.com/23353129/75256114-ece5cb00-581d-11ea-9d78-3d334de7c5a7.png)

**Comment by Wonder233** [comment]
复制粘贴卡死可能是因为网络波动问题导致复制请求超时无响应，超时的复制请求一直没有抛出错误让界面看起来卡住。

临时解决方案：
- 关闭客户端从而停止该复制请求
- 重新打开客户端进行复制，弹出的面板里操作选项选【跳过】则可跳过之前已成功复制过的文件

后续我们将会对复制粘贴进行优化：
- 复制粘贴请求增加请求超时时间，这样因为请求超时导致卡住的文件可以提前把错误抛出
- 复制粘贴任务支持取消
- 复制粘贴失败支持失败文件重试

谢谢您的反馈~

**Comment by Wonder233** [comment]
已优化。
