### ISSUE TITLE
就是来吐槽一下新版2.0的UI交互，切换桶变麻烦了

### ISSUE THREAD

**Issue by liqiang30080** [tencentyun/cosbrowser#95]
产品经理太水，越改体验越差。二级目录那里多香，嫌碍眼搞个折叠记住状态。一下就砍掉，砍你妹妹。

**Comment by liqiang30080** [comment]
有几百个桶，每次切换又给跑到最顶端去，又得拉下来慢慢找，我就问你水不水。

**Comment by liqiang30080** [comment]
我以为只有三流公司设计产品会这样欠缺考虑，原来腾讯大公司也会。

**Comment by carsonxu** [comment]
您好，感谢使用 cosbrowser，抱歉改版给你带来的不习惯。
1. 新界面改版本我们出多个交互方式调研过，更多用户选择当前这个版本的设计交互。
2. 下个版本我们增加左侧收起的存储桶列表菜单，支持固定展开。
3. 如果需要切换回老版本可从以上链接里获取下载地址：
https://github.com/tencentyun/cosbrowser/blob/master/changelog.md

**Comment by carsonxu** [comment]
2.1.0 已支持左侧展开存储桶列表

**Comment by canaan-yz** [comment]
特意过来夸一下UI👍，浅蓝色背景与蓝色主色统一并柔和区分，给设计师点赞。v2.1.3。

**Comment by carsonxu** [comment]
感谢点赞，我们持续优化功能和体验。
