### ISSUE TITLE
全部下载功能怎么没了？

### ISSUE THREAD

**Issue by zfben** [tencentyun/cosbrowser#96]
哪里可以下载旧版本吗？一下子没法用了

**Comment by carsonxu** [comment]
https://github.com/tencentyun/cosbrowser/blob/master/changelog.md

**Comment by carsonxu** [comment]
感谢使用，在这里可以下载 1.5.4 版本。
2.0.0 版本是遇到什么使用问题？

**Comment by zfben** [comment]
原来藏到右键菜单里了，吓我一跳以为没这个功能了
