### ISSUE TITLE
win10 用的2.0版COSBrowser 每次重新启动系统都会自动同步，请速速解决！！

### ISSUE THREAD

**Issue by RyanDx** [tencentyun/cosbrowser#97]
win10 用的2.0版COSBrowser 每次重新启动系统都会自动同步，请速速解决！！

**Comment by carsonxu** [comment]
谢谢反馈，这周内会有小版本修正。

**Comment by carsonxu** [comment]
我们再确认了下，老版本也会启动就同步。
你可以到文件同步里，停止同步任务。下次打开就不会同步。

**Comment by RyanDx** [comment]
每次开机同步所有的文件状态，检查一遍所有的文件要好长时间，这样太麻烦了吧

**Comment by carsonxu** [comment]
这里可以关掉自动同步。
如果开启自动同步，每次启动后是要严格对比一次的，不然不好保证和线上一致。

**Comment by RyanDx** [comment]
我用老版本没有这个问题，同步记录里没有同步日志，新版本会把每个文件都上传校验一遍，也是无语，这样会占用很大性能。你们可以这是一个触发机制啊，让用户选愿不愿意让它在关机前一直保持后台服务，只对不允许的用户，开机执行这种变态检查



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: carsonxu <notifications@github.com&gt;
发送时间: 2020年3月11日 15:11
收件人: tencentyun/cosbrowser <cosbrowser@noreply.github.com&gt;
抄送: Ryan.D <3608201@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[tencentyun/cosbrowser] win10 用的2.0版COSBrowser 每次重新启动系统都会自动同步，请速速解决！！ (#97)




这里可以关掉自动同步。
 如果开启自动同步，每次启动后是要严格对比一次的，不然不好保证和线上一致。

**Comment by carsonxu** [comment]
我们再确认下这里是否有区别，感谢及时回复。

**Comment by carsonxu** [comment]
这里确认了是每次打开只是重新校验了一遍，没有真正重新上传文件，下个版本优化文字提示。

**Comment by carsonxu** [comment]
已优化提示，校验不提示已上传
