### ISSUE TITLE
V2.0版本同一个账号登录一台机器上传另一台机器下载报错“没有下载权限”

### ISSUE THREAD

**Issue by lzhiyliu** [tencentyun/cosbrowser#98]
存储桶：host-lzhiyliu-1256846103
权限：共有读私有写
本机上传的图片下载查看无异常
![image](https://user-images.githubusercontent.com/42799259/75734374-c13d7600-5d32-11ea-9404-ca90d301df53.png)
跟换电脑后进行下载出现问题（同一个key）
![image](https://user-images.githubusercontent.com/42799259/75734443-ef22ba80-5d32-11ea-9071-ebd48db10786.png)

**Comment by Wonder233** [comment]
您好~
请跟换一下没有下载权限的那台电脑的本地时间，校正到正确的时间。
cosbrowser 之后会做一个校准时间优化，敬请期待~
