### ISSUE TITLE
吐槽一下把界面上的复制链接按钮取消了

### ISSUE THREAD

**Issue by jingjiecb** [tencentyun/cosbrowser#99]
我用这个来存博客中用到的图片，结果新版本把文件后面可以点一下就能复制链接的按钮取消了？？本来拖拽上传然后点一下就能引用链接，结果现在要点开详情再点复制，比原来还变麻烦了。
不过界面比原来好看了一点。
希望下个版本能够把复制链接（不是临时分享）的按钮再加上。

**Comment by carsonxu** [comment]
还是可以的，按钮换成“分享”的样子

**Comment by carsonxu** [comment]
![image](https://user-images.githubusercontent.com/24862812/75766224-c4108900-5d7b-11ea-81e0-33e77d7928ff.png)

**Comment by jingjiecb** [comment]
谢谢！
但是那个点了之后上面提示是一个小时内有效的临时链接，我希望能够保留原来的那个可以复制永久有效链接的，这样会比较方便。

**Comment by carsonxu** [comment]
这里是会判断文件是公有读时，复制的会是不带签名的 url。
看看是不是私有存储桶？

**Comment by jingjiecb** [comment]
哦这样啊，公读的桶确实可以。十分感谢！
新版本好评！
